### ISSUE TITLE
Plan more established social nights

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/org#63] opened 2017-10-26 20:44 UTC
Plan social nights a head of time, keep them mixed up, fun and exciting. Also insure the meetup description is engaging.

**Comment by davidbhayes** [comment] 2017-11-10 02:23
This feels like a dupe of #48. Ima close for that. But if it's different please reopen and clarify :)

**Closed as completed by davidbhayes** 2017-11-10 02:23 UTC
